import pandas as pd

ad_clicks = pd.read_csv('ad_clicks.csv')
print(ad_clicks.head())
utm_sources = ad_clicks.groupby('utm_source').user_id.count().reset_index()
print(utm_sources)
ad_clicks['is_click'] = ad_clicks.ad_click_timestamp.apply(lambda x: True if x == x else False)
print(ad_clicks)
clicks_by_source = ad_clicks.groupby(['utm_source', 'is_click']).user_id.count().reset_index()
print(clicks_by_source)
clicks_pivot = clicks_by_source.pivot(columns='is_click', index='utm_source', values='user_id').reset_index()
print(type(ad_clicks))
print(type(clicks_pivot))
print(clicks_pivot)
#clicks_pivot['percent_clicked'] = clicks_pivot.apply(lambda row: row['True'] / (row['False'] + row['True']), axis=1)
clicks_pivot['percent_clicked'] = clicks_pivot[True] / (clicks_pivot[True] + clicks_pivot[False])
print(clicks_pivot)
groups_sizes = ad_clicks.groupby('experimental_group').user_id.count().reset_index()
print(groups_sizes)
ab_clicked = ad_clicks.groupby(['experimental_group', 'is_click']).user_id.count().reset_index()
print(ab_clicked)
ab_clicks_pivot = ab_clicked.pivot(columns='is_click', index='experimental_group', values='user_id').reset_index()
print(ab_clicks_pivot)
a_clicks = ad_clicks[ad_clicks.experimental_group == 'A']
b_clicks = ad_clicks[ad_clicks.experimental_group == 'B']
print(a_clicks)
print(b_clicks)
a_by_day = a_clicks.groupby(['is_click', 'day']).user_id.count().reset_index()
b_by_day = b_clicks.groupby(['is_click', 'day']).user_id.count().reset_index()
print(a_by_day)
print(b_by_day)
a_by_day_pivot = a_by_day.pivot(columns='is_click', index='day', values='user_id').reset_index()
b_by_day_pivot = b_by_day.pivot(columns='is_click', index='day', values='user_id').reset_index()
print(a_by_day_pivot)
print(b_by_day_pivot)
a_by_day_pivot['percent_clicked'] = a_by_day_pivot[True] / (a_by_day_pivot[True] + a_by_day_pivot[False])
b_by_day_pivot['percent_clicked'] = b_by_day_pivot[True] / (b_by_day_pivot[True] + b_by_day_pivot[False])
print(a_by_day_pivot)
print(b_by_day_pivot)
